export const text = `
1. Acceptance of Terms: By utilizing the services provided by OpportuLand ("we," "our," or "us"), you agree to adhere to and be bound by these terms and conditions ("Terms"). If you do not agree to these Terms, kindly refrain from using our services.
2. Eligibility: Our services are designed for individuals aged 18 or older. By accessing or using our services, you confirm that you are at least 18 years old.
3. User Registration: To access specific features of our services, you may need to register for an account. You agree to provide accurate, current, and complete information during the registration process. You are responsible for keeping your login credentials confidential and for any activity that occurs under your account.
4. Use of Services: You are granted a limited, non-exclusive, non-transferable, and revocable license to use our services for personal, non-commercial purposes. You agree not to engage in any unlawful or unauthorized activities and to comply with all applicable laws.
5. User Content: Any data, text, or other content ("User Content") that you submit to our services remains your property. By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free license to use, copy, modify, and distribute your User Content for the purpose of providing our services.
6. Resume Licensing and Modification: Users grant OpportuLand the right to license and modify their resumes for the purpose of enhancing their job application chances.
7. Cover Letter Generation: OpportuLand may use AI technology to generate cover letters based on the user's resume and modify resume to enhance their job applications.
8. Job Applications on Behalf of Users: OpportuLand has the right to submit job applications on behalf of users, including answering questions posed by job boards to complete applications or sign up on platforms to the best of its capabilities.
9. Email Creation and Access: Upon user registration, OpportuLand creates an email address for the user and retains access for the purpose of sending out job applications and retrieving necessary data.
10. Connecting Personal Email: If user chooses to connect their own email address (this is up to the user), the user grants OpportuLand with the right to access to the provided email. The grant is only used for applying to jobs using the provided email account and read the responses to show on the app related to the applied jobs.
11. Refund Policy: We do not provide refunds for any fees or charges related to our services.
12. User Responsibilities: You agree not to misuse our services, including but not limited to avoiding any automated access and complying with the terms and conditions of external job boards when using our application services.
13. Intellectual Property: All content provided by OpportuLand, including trademarks, logos, and service marks, is the property of OpportuLand or our content suppliers and is protected by applicable intellectual property laws.
14. Termination of Services: We reserve the right to terminate or suspend your access to Four services at our discretion, without notice and for any reason, including violation of these Terms.
15. Disclaimer of Warranties: Our services are provided "as is" and "as available" without warranties of any kind, whether express or implied. We do not warrant that our services will be uninterrupted, secure, or error-free.
16. Limitation of Liability: In no event shall OpportuLand be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your access to or use of our services.
17. Governing Law: These Terms are governed by and construed in accordance with the laws of the Republic of Azerbaijan, without regard to its conflict of law principles.
18. Amendments: We reserve the right to modify these Terms at any time. The most current version will be available on our platform. Your continued use of our services after any modifications constitute acceptance of those changes.
19. Contact Information: For any questions aboutF these Terms, please contact us at remoteap@remote-auto.com.
20. Entire Agreement: These Terms constitute the entire agreement between you and OpportuLand, superseding any prior agreements or understandings. Any failure by us to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.
21. Ownership of Contest Submissions: By participating in contests hosted on our platform, you transfer all intellectual property rights, title, and interest in your submissions to OpportuLand. This includes full ownership of any text, images, or other materials provided. OpportuLand will have the exclusive rights to use, copy, modify, display, and distribute these submissions as we see fit, including for promotional purposes.
22. Business Contest Content: Businesses creating contests on our platform agree to transfer all intellectual property rights, title, and interest in any content associated with their contests to OpportuLand. This includes, but is not limited to, promotional materials, contest submissions, and any related intellectual property. OpportuLand will have exclusive rights to use, copy, modify, display, and distribute this content.
23. Rights to Showcase Content: OpportuLand has the exclusive right to feature any contest submissions or content as we choose, including in upvote sections, promotional materials, and on our platform. By participating or submitting content, you agree that OpportuLand has full ownership and control over how this content is used and displayed.
24. No Compensation for Featured Content: Participants and businesses acknowledge that showcasing their content as part of the contest or in upvote sections does not entitle them to any additional compensation or rights beyond the contest prizes or awards.
25. Award Compliance: Businesses who create contests on our platform are obligated to fulfill the promised awards as specified in their contest listings. OpportuLand is not responsible for any failure by the contest organizers to deliver the promised awards. In the event of non-compliance by a business, participants are encouraged to contact us, and we will assist in mediating the issue, but final responsibility for awarding rests with the contest organizer.
26. Business Responsibilities for Awards: Businesses creating contests must:
Clearly specify the awards and their value in the contest listing.
Ensure that awards are provided to winners within the timeframe stated in the contest rules.
Comply with all relevant laws and regulations related to awarding prizes.
27. Dispute Resolution: If a participant believes that a business has failed to fulfill their award obligations, they should notify OpportuLand within [specify timeframe, e.g., 30 days] of the contest's conclusion. OpportuLand will review the complaint and may contact the business for clarification. While we will attempt to assist in resolving disputes, we do not guarantee compensation or resolution.
28. Indemnification: By creating a contest, businesses agree to indemnify and hold OpportuLand harmless from any claims, damages, or liabilities arising from their failure to provide promised awards. This includes covering any legal fees or costs incurred by OpportuLand in relation to disputes over awards.
29.Contingency for Non-Compliance: OpportuLand reserves the right to take action against businesses that fail to fulfill their award commitments. This may include suspending or terminating the business’s ability to create future contests on our platform, as well as taking other actions as deemed appropriate.
`

export const title = `OpportuLand Terms and Conditions`
export const date =`Effective Date: 21.11.2023`